### ISSUE TITLE
Underwater Calibration of RealSense camera in FishSense Project

### ISSUE THREAD

**Issue by robotlearning123** [justlee0606/fishsense-boxdraw#1]
Hi Justin,
I am interested in your project [FishSense](http://e4e.ucsd.edu/fishsense?fbclid=IwAR067-tL5Zz2nRY2b4OUIJVYd5s5XlmNSdfkS5Lor1uZOXrp6imQBeADPac). 
These videos look very good:

https://youtu.be/ey7oqCiqm6o
https://youtu.be/-aETBlM_tkc

Recently, we have a dicussion about the underwater calibration of RealSense Camera: https://github.com/IntelRealSense/realsense-ros/issues/1723#issuecomment-802757664. 

I think you should have experience about this. Could you give some advice about it? It would be most appreciated if you could help.

Thanks a lot!

**Comment by justlee0606** [comment]
Hello Cong,

Thank you for your interest in our project. I actually only recently joined
this project, so I do not have much experience on the IntelRealSense
technology myself. However, feel free to reach out to one of our project
leads, his name is Peter and he is very knowledgeable on your requests. His
email is ***@***.***

Best,
Justin

**Comment by justlee0606** [comment]
Hello Cong,

Thank you for your interest in our project. I actually only recently joined this project, so I do not have much experience on the IntelRealSense technology myself. However, feel free to reach out to one of our project leads, his name is Peter and he is very knowledgeable on your requests. His email is ptueller@eng.ucsd.edu.

Best,
Justin

**Comment by robotlearning123** [comment]
Thank you a lot!
